<a href="https://colab.research.google.com/github/alvas-education-foundation/Melita-1999/blob/master/day%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
#ds = pd.Series([2, 4, 6, 8..... 10]) 
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [3]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


In [5]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [6]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [7]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


In [8]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [9]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


In [10]:

import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


In [11]:

import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


In [12]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


In [13]:

import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


In [14]:

import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [15]:

import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


In [16]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [17]:

import numpy as np
x = np.random.normal(size=5)
print(x)

[-0.09141208 -1.09593684  0.42875348 -0.59898584 -0.49295931]


In [18]:

import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[12 15 24 20 20 15]


In [19]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.44530491 0.81477876 0.20545399]
  [0.55384979 0.5602544  0.24483614]
  [0.82273194 0.77190902 0.60260287]]

 [[0.42888905 0.36371875 0.0710939 ]
  [0.91558575 0.7193304  0.67825426]
  [0.10157207 0.56549209 0.76931671]]

 [[0.93500133 0.69021104 0.43003408]
  [0.98579416 0.1569058  0.9280209 ]
  [0.47850396 0.64325766 0.44577216]]]


In [20]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.02869333 0.70195375 0.71549519 0.48719845 0.02520259]
 [0.29267157 0.64616539 0.26310926 0.27137639 0.2627647 ]
 [0.90852046 0.8075682  0.38228071 0.2667346  0.38312303]
 [0.31617868 0.32574075 0.76774433 0.97220323 0.57648025]
 [0.81955712 0.62712223 0.3711536  0.33944316 0.57940232]]
Minimum and Maximum Values:
0.025202591554464804 0.9722032253882639


In [21]:

import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.69016719 0.47611639 0.74504112 0.7892878 ]
 [0.52215051 0.45852619 0.25895597 0.61589232]
 [0.23616848 0.83065319 0.65794509 0.09932342]
 [0.28331129 0.69937156 0.98095304 0.35473118]
 [0.87836616 0.12633536 0.19101872 0.92077762]
 [0.16344749 0.06933572 0.87794774 0.36694597]
 [0.37082417 0.73378611 0.0590414  0.64448889]
 [0.34844595 0.06039653 0.53883044 0.24001908]
 [0.19152933 0.42049395 0.05767305 0.06479663]
 [0.95191177 0.65647194 0.977451   0.46565916]]
First 5 rows of the above array:
[[0.69016719 0.47611639 0.74504112 0.7892878 ]
 [0.52215051 0.45852619 0.25895597 0.61589232]
 [0.23616848 0.83065319 0.65794509 0.09932342]
 [0.28331129 0.69937156 0.98095304 0.35473118]
 [0.87836616 0.12633536 0.19101872 0.92077762]]
First 3 columns of the above array:
[[0.69016719 0.47611639 0.74504112 0.7892878 ]
 [0.52215051 0.45852619 0.25895597 0.61589232]
 [0.23616848 0.83065319 0.65794509 0.09932342]
 [0.28331129 0.69937156 0.98095304 0.35473118]
 [0.87836616 0.1263

In [22]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[6 1 9 5 0 2 3 8 7 4]
Same result using permutation():
[5 3 0 4 7 2 1 9 6 8]


In [23]:
import numpy as np
x=np.arange(10)
np.random.randint(10)
print (x)

[0 1 2 3 4 5 6 7 8 9]


In [24]:

import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[3 7 6 2 1 9 5 4 8 0]
[0 1 2 3 4 5 6 7 8 9]
